# Generated by Django 3.1 on 2020-11-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=64)),
                ('carPicture', models.CharField(max_length=64)),
                ('seats', models.IntegerField()),
                ('trunk', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('fuel', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='rental',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cars'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
