# Generated by Django 3.1 on 2020-11-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201113_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.CharField(default='manualna', max_length=64),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(default='benzyna', max_length=64),
        ),
    ]
