# Generated by Django 3.1 on 2020-08-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_transfer_last_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='last_transfer',
            field=models.DateField(auto_now=True),
        ),
    ]
