# Generated by Django 3.1 on 2020-09-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transfer_last_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.BigIntegerField(unique=True),
        ),
    ]
