# Generated by Django 3.1 on 2020-10-01 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20200926_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOfTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcs', models.IntegerField()),
                ('date_transfer', models.DateField(auto_now=True)),
                ('locationFrom', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromLocation', to='api.location')),
                ('locationTo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='toLocation', to='api.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
