# Generated by Django 3.1 on 2020-10-01 18:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_historyoftransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historyoftransfer',
            name='locationFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromLocation', to='api.location'),
        ),
        migrations.AlterField(
            model_name='historyoftransfer',
            name='locationTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toLocation', to='api.location'),
        ),
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcs', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurantproduct')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restauranttable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
